# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [5]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [6]:
# Create a 1-dimensional NumPy array using np.array()
arr_1 = np.array([1, 2, 3, 4, 5, 6])
arr_1

array([1, 2, 3, 4, 5, 6])

In [7]:
# Create a 2-dimensional NumPy array using np.array()
arr_2 = np.array([[3,4,6],
                  [5,6,8]])
arr_2

array([[3, 4, 6],
       [5, 6, 8]])

In [8]:
# Create a 3-dimensional Numpy array using np.array()
arr_3 = np.array([[[2,4,6,7],
                   [5,7,9,10],
                   [4,7,9,1]]])
arr_3

array([[[ 2,  4,  6,  7],
        [ 5,  7,  9, 10],
        [ 4,  7,  9,  1]]])

In [9]:
# Attributes of 1-dimensional array (shape,
arr_1.shape

(6,)

In [10]:
arr_2.shape

(2, 3)

In [11]:
arr_3.shape

(1, 3, 4)

In [12]:
 # number of dimensions, data type, size and type)
arr_1.ndim, arr_2.ndim, arr_3.ndim

(1, 2, 3)

In [13]:
# data type
arr_1.dtype, arr_2.dtype, arr_3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [14]:
# size
arr_1.size, arr_2.size, arr_3.size

(6, 6, 12)

In [15]:
# type
type(arr_1), type(arr_2), type(arr_3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
# Import pandas and create a DataFrame out of one
import pandas as pd
arr_1_df  = pd.DataFrame(arr_1)
arr_1_df

0
0  1
1  2
2  3
3  4
4  5
5  6

In [17]:
arr_2_df = pd.DataFrame(arr_2)
arr_2_df

0  1  2
0  3  4  6
1  5  6  8

In [18]:
# Create an array of shape (10, 2) with only ones
Ones = np.ones((10,2))
Ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
# Create an array of shape (7, 2, 3) of only zeros
Ones_2 = np.ones((7, 2, 3))
Ones_2


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
zeros =np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
# Create an array within a range of 0 and 100 with step 3
arr_4 = np.arange(0, 100, 3)
arr_4


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [22]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
import random as random
arr_5 = np.random.randint(10, size=(7, 2))
arr_5


array([[9, 0],
       [7, 5],
       [0, 3],
       [8, 6],
       [1, 8],
       [2, 5],
       [0, 2]])

In [23]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_6 = np.random.random((3, 5))
arr_6

array([[0.68181875, 0.56007211, 0.99566311, 0.73617792, 0.9670298 ],
       [0.76798518, 0.35130643, 0.94375276, 0.42381028, 0.85058959],
       [0.31956031, 0.86622565, 0.40039283, 0.07268565, 0.56584688]])

In [24]:
# Set the random seed to 42
np.random.seed(42)
arr_7 = np.random.random((3,5))
arr_7

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497]])

In [25]:
# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.seed(42)
arr_8 = np.random.randint(10, size=(4, 6))
arr_8

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?
the values stopped changing

Are the numbers in the array different or the same? Why do think this is?
the seed attribute locked it

In [26]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
# Find the unique numbers in the array you just created
arr_9 = np.random.randint(1, 10, size=(3, 7))
arr_9, np.unique(arr_9)

(array([[9, 1, 3, 7, 4, 9, 3],
        [5, 3, 7, 5, 9, 7, 2],
        [4, 9, 2, 9, 5, 2, 4]]),
 array([1, 2, 3, 4, 5, 7, 9]))

In [27]:
# Find the 0'th index of the latest array you created
arr_9[0], arr_9[1]


(array([9, 1, 3, 7, 4, 9, 3]), array([5, 3, 7, 5, 9, 7, 2]))

In [32]:
arr_9

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [36]:
# Get the first 2 rows of latest array you created
arr_9[:2]


array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [37]:
# Get the first 2 values of the first 2 rows of the latest array
arr_9[:2, :2]


array([[9, 1],
       [5, 3]])

In [40]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr_10 = np.random.randint(0, 10, size=(3,5))
arr_11 = np.ones((3,5))

In [42]:
arr_10, arr_11

(array([[0, 8, 6, 8, 7],
        [0, 7, 7, 2, 0],
        [7, 2, 2, 0, 4]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [43]:
# Add the two arrays together
arr_10 + arr_11


array([[1., 9., 7., 9., 8.],
       [1., 8., 8., 3., 1.],
       [8., 3., 3., 1., 5.]])

In [44]:
# Create another array of ones of shape (5, 3)
arr_12 = np.ones((5,3))
arr_12

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
# Try add the array of ones and the other most recent array together
arr_10 + arr_12


ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?
because they are not of equal shapes

How would you fix it?
I will have to tranpose one of them

In [51]:
# Create another array of ones of shape (3, 5)
np.random.seed(12)
arr_13 = np.random.random((3, 5))
arr_13


array([[0.15416284, 0.7400497 , 0.26331502, 0.53373939, 0.01457496],
       [0.91874701, 0.90071485, 0.03342143, 0.95694934, 0.13720932],
       [0.28382835, 0.60608318, 0.94422514, 0.85273554, 0.00225923]])

In [52]:
# Subtract the new array of ones from the other most recent array
arr_10 - arr_13

array([[-0.15416284,  7.2599503 ,  5.73668498,  7.46626061,  6.98542504],
       [-0.91874701,  6.09928515,  6.96657857,  1.04305066, -0.13720932],
       [ 6.71617165,  1.39391682,  1.05577486, -0.85273554,  3.99774077]])

In [53]:
# Multiply the ones array with the latest array
arr_11 * arr_13

array([[0.15416284, 0.7400497 , 0.26331502, 0.53373939, 0.01457496],
       [0.91874701, 0.90071485, 0.03342143, 0.95694934, 0.13720932],
       [0.28382835, 0.60608318, 0.94422514, 0.85273554, 0.00225923]])

In [54]:
# Take the latest array to the power of 2 using '**'
arr_13 ** 2


array([[2.37661820e-02, 5.47673553e-01, 6.93347972e-02, 2.84877740e-01,
        2.12429531e-04],
       [8.44096065e-01, 8.11287248e-01, 1.11699182e-03, 9.15752032e-01,
        1.88263979e-02],
       [8.05585339e-02, 3.67336826e-01, 8.91561108e-01, 7.27157903e-01,
        5.10413609e-06]])

In [55]:
# Do the same thing with np.square()
np.square(arr_13)

array([[2.37661820e-02, 5.47673553e-01, 6.93347972e-02, 2.84877740e-01,
        2.12429531e-04],
       [8.44096065e-01, 8.11287248e-01, 1.11699182e-03, 9.15752032e-01,
        1.88263979e-02],
       [8.05585339e-02, 3.67336826e-01, 8.91561108e-01, 7.27157903e-01,
        5.10413609e-06]])

In [56]:
# Find the mean of the latest array using np.mean()
np.mean(arr_13)


0.48946768702786525

In [57]:
# Find the maximum of the latest array using np.max()
np.max(arr_13)


0.9569493362751168

In [58]:
# Find the minimum of the latest array using np.min()
np.min(arr_13)


0.002259233518513537

In [59]:
# Find the standard deviation of the latest array
np.std(arr_13)

0.3642237098901014

In [60]:
# Find the variance of the latest array
np.var(arr_13)


0.13265891084610873

In [61]:
# Reshape the latest array to (3, 5, 1)
arr_13.reshape(3, 5, 1)


array([[[0.15416284],
        [0.7400497 ],
        [0.26331502],
        [0.53373939],
        [0.01457496]],

       [[0.91874701],
        [0.90071485],
        [0.03342143],
        [0.95694934],
        [0.13720932]],

       [[0.28382835],
        [0.60608318],
        [0.94422514],
        [0.85273554],
        [0.00225923]]])

In [62]:
# Transpose the latest array
arr_13.T


array([[0.15416284, 0.91874701, 0.28382835],
       [0.7400497 , 0.90071485, 0.60608318],
       [0.26331502, 0.03342143, 0.94422514],
       [0.53373939, 0.95694934, 0.85273554],
       [0.01457496, 0.13720932, 0.00225923]])

What does the transpose do?
It changed the shape from (3, 5) to (5, 3)

In [66]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr_14 = np.random.randint(0, 10, size=(3, 3))
arr_15 = np.random.randint(0, 10, size=(3, 2))
arr_14, arr_15


(array([[5, 3, 4],
        [5, 5, 0],
        [6, 6, 3]]),
 array([[2, 4],
        [3, 9],
        [6, 7]]))

In [67]:
# Perform a dot product on the two newest arrays you created
np.dot(arr_14, arr_15)


array([[43, 75],
       [25, 65],
       [48, 99]])

In [70]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr_16 = np.random.randint(0, 10, size=(4,3))
arr_17 = np.random.randint(0, 10, size=(4,3))
arr_16, arr_17


(array([[4, 3, 8],
        [8, 6, 9],
        [8, 4, 9],
        [4, 1, 4]]),
 array([[1, 4, 3],
        [2, 8, 0],
        [1, 4, 6],
        [5, 4, 2]]))

In [71]:
# Perform a dot product on the two newest arrays you created
np.dot(arr_16, arr_17)


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?
I would have to transpose one of them.

In [73]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr_16.T
np.dot(arr_16.T, arr_17)

array([[ 48, 128,  68],
       [ 24,  80,  35],
       [ 55, 156,  86]])

In [74]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr_16 > arr_17


array([[ True, False,  True],
       [ True, False,  True],
       [ True, False,  True],
       [False, False,  True]])

In [75]:
# Find which elements of the first array are greater than 7
arr_16 > 7


array([[False, False,  True],
       [ True, False,  True],
       [ True, False,  True],
       [False, False, False]])

In [76]:
# Which parts of each array are equal? (try using '==')
arr_16 == arr_17

array([[False, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False]])

In [79]:
# Sort one of the arrays you just created in ascending order
np.sort(arr_17), arr_17


(array([[1, 3, 4],
        [0, 2, 8],
        [1, 4, 6],
        [2, 4, 5]]),
 array([[1, 4, 3],
        [2, 8, 0],
        [1, 4, 6],
        [5, 4, 2]]))

In [81]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr_17)


array([[0, 2, 1],
       [2, 0, 1],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [82]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr_16), np.argmax(arr_17)


(5, 4)

In [83]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr_16)

10

In [84]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr_16, axis=1)

array([2, 2, 2, 0], dtype=int64)

In [85]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr_17, axis=0)


array([0, 0, 1], dtype=int64)

In [93]:
# Create an array of normally distributed random numbers
arr_18 = np.random.randn(1, 100, 10)
arr_18

array([[[ 1.37503811e+00, -5.68490265e-01,  5.79789641e-01,
          1.32747523e+00,  2.71421772e-01,  1.01902088e+00,
          1.16997592e+00, -1.31630706e-01,  4.81753935e-01,
         -4.97742333e-01],
        [ 1.43959413e+00,  2.61567910e-01, -2.27635057e+00,
         -4.63041960e-01,  1.07111079e+00, -1.03057129e+00,
         -3.98819772e-01,  1.21704611e-01,  1.12941974e+00,
         -1.61917499e+00],
        [ 8.27834028e-01, -4.49019287e-01,  1.86799427e+00,
          7.18303280e-01,  8.15586153e-01,  6.58826379e-01,
          5.45765710e-01, -2.41621067e+00, -1.08808852e+00,
          7.89301312e-01],
        [ 7.15852271e-01,  1.34512942e+00, -1.27446641e+00,
         -4.56859932e-01, -5.56199910e-02, -7.00294045e-02,
          1.05620975e-01, -4.95417313e-01,  4.24753393e-01,
          2.36823260e-01],
        [ 1.00309600e-01,  4.91737071e-01, -2.44300968e+00,
          2.88556781e-01,  1.54577588e+00,  7.94025973e-01,
          6.21360333e-01, -1.06070907e-01, -4.923716

In [91]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr_19 = np.linspace(1, 100, 10)
arr_19


array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])